# Generated by Django 5.2.1 on 2025-06-04 19:38

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=3000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_type', models.CharField(choices=[('OBJ', 'Wavefront OBJ'), ('STL', 'Stereolithography'), ('FBX', 'Autodesk FBX'), ('BLEND', 'Blender'), ('GLTF', 'GL Transmission Format')], max_length=10)),
                ('file_size', models.PositiveIntegerField(verbose_name='Размер файла (в байтах)')),
                ('file', models.FileField(upload_to='3d_models/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['obj', 'stl', 'fbx', 'blend', 'gltf'])], verbose_name='Файл 3D-модели')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена в рублях')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Количество скачиваний')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': '3D модели',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['title'],
            },
        ),
    ]
