# Generated by Django 5.2.1 on 2025-06-04 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model3d', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='model3d',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='models', to='products.tag', verbose_name='Теги'),
        ),
        migrations.AddIndex(
            model_name='model3d',
            index=models.Index(fields=['-created_at'], name='idx_created_at_desc'),
        ),
        migrations.AddIndex(
            model_name='model3d',
            index=models.Index(fields=['author'], name='idx_author'),
        ),
        migrations.AddIndex(
            model_name='model3d',
            index=models.Index(fields=['title'], name='idx_title'),
        ),
    ]
