# Generated by Django 5.2.1 on 2025-06-06 09:47

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(max_length=50, unique=True, verbose_name='Тип лицензии')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
                'ordering': ['license_type'],
            },
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='ModelTag',
        ),
        migrations.AlterModelOptions(
            name='model3d',
            options={'ordering': ['-created_at'], 'verbose_name': '3D модель', 'verbose_name_plural': '3D модели'},
        ),
        migrations.AddField(
            model_name='model3d',
            name='animated',
            field=models.BooleanField(default=False, verbose_name='Анимированная модель.'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='file',
            field=models.FileField(upload_to='3d_models/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['obj', 'glb', 'fbx', 'blend'])], verbose_name='Файл 3D-модели'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='file_type',
            field=models.CharField(choices=[('OBJ', 'Wavefront OBJ'), ('GLB', 'GL Transmission Format Binary file'), ('FBX', 'Autodesk FBX'), ('BLEND', 'Blender')], max_length=10),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Цена в долларах США'),
        ),
        migrations.CreateModel(
            name='ModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/srv/ftp/market_3d_storage/previews'), upload_to='model_images/%Y/%m/%d/', verbose_name='Изображение превью')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.model3d', verbose_name='3D-модель')),
            ],
            options={
                'verbose_name': 'Изображение модели',
                'verbose_name_plural': 'Изображения моделей',
            },
        ),
        migrations.AddField(
            model_name='model3d',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='products.modellicense', verbose_name='Тип лицензии'),
        ),
    ]
