# Generated by Django 5.2.1 on 2025-06-07 18:18

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_modellicense_rename_tag_modeltag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='nft_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='NFT-токен (опционально)'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/srv/ftp/market_3d_storage/models'), upload_to='3d_models/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['obj', 'glb', 'fbx', 'blend'])], verbose_name='Файл 3D-модели'),
        ),
    ]
